# Generated by Django 3.1.7 on 2021-05-13 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210420_0100'),
        ('like', '0002_auto_20210513_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.PositiveIntegerField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.post'),
            preserve_default=False,
        ),
    ]
