# Generated by Django 3.1.7 on 2021-05-13 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0003_auto_20210513_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
    ]
