# Generated by Django 3.1.7 on 2021-05-13 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0004_auto_20210513_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
    ]
